## Dataset preprocessing

In [7]:
import pandas as pd
import os

In [8]:
df = pd.read_csv("../data/processed/fraud_detection_dataset.csv")
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,Previous_Fraudulent_Activity,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Fraud_Label
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,Amex,65,883.17,Biometric,0.8494,0
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,Mastercard,186,2203.36,Password,0.0959,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,Visa,226,1909.29,Biometric,0.8400,1
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,Visa,76,1311.86,OTP,0.7935,1
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,1,Mastercard,140,966.98,Password,0.3819,1

In [9]:
df.columns

Index(['Transaction_Amount', 'Transaction_Type', 'Account_Balance',
       'Device_Type', 'Location', 'Merchant_Category',
       'Previous_Fraudulent_Activity', 'Card_Type', 'Card_Age',
       'Transaction_Distance', 'Authentication_Method', 'Risk_Score',
       'Fraud_Label'],
      dtype='object')

In [10]:
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,Previous_Fraudulent_Activity,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Fraud_Label
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,Amex,65,883.17,Biometric,0.8494,0
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,Mastercard,186,2203.36,Password,0.0959,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,Visa,226,1909.29,Biometric,0.8400,1
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,Visa,76,1311.86,OTP,0.7935,1
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,1,Mastercard,140,966.98,Password,0.3819,1

In [11]:
df = pd.get_dummies(df, columns=[
    "Transaction_Type",
    "Device_Type",
    "Location",
    "Merchant_Category",
    "Card_Type",
    "Authentication_Method"
])

In [12]:
df.head()

,Transaction_Amount,Account_Balance,Previous_Fraudulent_Activity,Card_Age,Transaction_Distance,Risk_Score,Fraud_Label,Transaction_Type_ATM Withdrawal,Transaction_Type_Bank Transfer,Transaction_Type_Online,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,65,883.17,0.8494,0,False,False,False,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,186,2203.36,0.0959,1,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,226,1909.29,0.8400,1,False,False,True,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,76,1311.86,0.7935,1,True,False,False,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,1,140,966.98,0.3819,1,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [13]:
df["Fraud_Label"].value_counts()

Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

In [14]:
df.columns

Index(['Transaction_Amount', 'Account_Balance', 'Previous_Fraudulent_Activity',
       'Card_Age', 'Transaction_Distance', 'Risk_Score', 'Fraud_Label',
       'Transaction_Type_ATM Withdrawal', 'Transaction_Type_Bank Transfer',
       'Transaction_Type_Online', 'Transaction_Type_POS', 'Device_Type_Laptop',
       'Device_Type_Mobile', 'Device_Type_Tablet', 'Location_London',
       'Location_Mumbai', 'Location_New York', 'Location_Sydney',
       'Location_Tokyo', 'Merchant_Category_Clothing',
       'Merchant_Category_Electronics', 'Merchant_Category_Groceries',
       'Merchant_Category_Restaurants', 'Merchant_Category_Travel',
       'Card_Type_Amex', 'Card_Type_Discover', 'Card_Type_Mastercard',
       'Card_Type_Visa', 'Authentication_Method_Biometric',
       'Authentication_Method_OTP', 'Authentication_Method_PIN',
       'Authentication_Method_Password'],
      dtype='object')

In [15]:
df.head()

,Transaction_Amount,Account_Balance,Previous_Fraudulent_Activity,Card_Age,Transaction_Distance,Risk_Score,Fraud_Label,Transaction_Type_ATM Withdrawal,Transaction_Type_Bank Transfer,Transaction_Type_Online,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,65,883.17,0.8494,0,False,False,False,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,186,2203.36,0.0959,1,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,226,1909.29,0.8400,1,False,False,True,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,76,1311.86,0.7935,1,True,False,False,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,1,140,966.98,0.3819,1,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [16]:
os.makedirs('../data/', exist_ok=True)
#Saving selected dataframe
df.to_csv('../data/processed/fraud_detection_dataset_preprocessed.csv', index=False)