## Testing different classification models

In [143]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [144]:
df = pd.read_csv("../data/processed/fraud_detection_dataset_preprocessed.csv")
df.head()

,Transaction_Amount,Account_Balance,Previous_Fraudulent_Activity,Card_Age,Transaction_Distance,Risk_Score,Fraud_Label,Transaction_Type_ATM Withdrawal,Transaction_Type_Bank Transfer,Transaction_Type_Online,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,65,883.17,0.8494,0,False,False,False,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,186,2203.36,0.0959,1,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,226,1909.29,0.8400,1,False,False,True,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,76,1311.86,0.7935,1,True,False,False,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,1,140,966.98,0.3819,1,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [145]:
X = df.drop(columns=["Fraud_Label"])
y = df["Fraud_Label"]

In [146]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [147]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [148]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train_res = pd.DataFrame(
    ss.fit_transform(X_train_res),
    columns=X.columns
)

X_test = pd.DataFrame(
    ss.transform(X_test),
    columns=X.columns
)

In [149]:
X_train_res.head()

,Transaction_Amount,Account_Balance,Previous_Fraudulent_Activity,Card_Age,Transaction_Distance,Risk_Score,Transaction_Type_ATM Withdrawal,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,-0.171306,1.692495,-0.281986,-0.402182,-1.009160,0.631434,1.539006,-0.65301,-0.654385,-0.657334,...,1.764588,-0.565086,-0.643332,1.540635,-0.660221,-0.661763,-0.656613,-0.654352,1.523423,-0.651929
1,-0.018709,0.389940,-0.281986,-0.824532,0.534634,-1.029912,-0.649770,-0.65301,-0.654385,1.521296,...,-0.566704,-0.565086,-0.643332,1.540635,-0.660221,-0.661763,1.522967,-0.654352,-0.656416,-0.651929
2,0.050302,0.301066,-0.281986,0.246428,1.454511,0.464706,1.539006,-0.65301,-0.654385,-0.657334,...,-0.566704,-0.565086,-0.643332,-0.649083,-0.660221,1.511114,-0.656613,1.528229,-0.656416,-0.651929
3,-1.029983,-0.168508,-0.281986,0.593358,-1.168400,1.409263,1.539006,-0.65301,-0.654385,-0.657334,...,-0.566704,1.769642,1.554407,-0.649083,-0.660221,-0.661763,-0.656613,-0.654352,-0.656416,1.533908
4,-0.922608,0.271913,3.546270,-0.884868,1.364382,1.242536,1.539006,-0.65301,-0.654385,-0.657334,...,-0.566704,-0.565086,-0.643332,-0.649083,-0.660221,1.511114,-0.656613,-0.654352,1.523423,-0.651929

In [150]:
y_train

8950     0
38421    0
19363    0
30157    1
14294    1
        ..
43723    0
32511    0
5192     1
12172    1
33003    0
Name: Fraud_Label, Length: 35000, dtype: int64

### Logistic Regression

In [151]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000, random_state=1)
lr.fit(X_train_res, y_train_res)
y_pred_lr = lr.predict(X_test)

In [152]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85     10141
           1       0.74      0.51      0.61      4859

    accuracy                           0.78     15000
   macro avg       0.77      0.71      0.73     15000
weighted avg       0.78      0.78      0.77     15000

### Random Forest

In [153]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=2, random_state=1)
rf.fit(X_train_res, y_train_res)
y_pred_rf = rf.predict(X_test)

In [154]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     10141
           1       1.00      0.47      0.64      4859

    accuracy                           0.83     15000
   macro avg       0.90      0.74      0.76     15000
weighted avg       0.86      0.83      0.81     15000

### Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.05, max_depth=1, random_state=1)
gbc.fit(X_train_res, y_train_res)
y_pred_gbc = gbc.predict(X_test)

In [156]:
print(classification_report(y_test, y_pred_gbc))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     10141
           1       1.00      0.47      0.64      4859

    accuracy                           0.83     15000
   macro avg       0.90      0.74      0.76     15000
weighted avg       0.86      0.83      0.81     15000

### Naive Bayes

In [157]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_res, y_train_res)
y_pred_nb = nb.predict(X_test)

In [158]:
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80     10141
           1       0.57      0.51      0.54      4859

    accuracy                           0.72     15000
   macro avg       0.68      0.67      0.67     15000
weighted avg       0.71      0.72      0.71     15000

Recall, informuje jaki procent oszustw został wykryty przez model.
Precision mówi o jak często model miał rację, gdy przewidzi oszustwo.
W tym przypadku priorytezowany jest recall.